#!/bin/bash

# Call ./get_module for each module
ZMAN_PATH=

# Defining lock file name
lock_file=$ZMAN_PROJECT_PATH/.zman.modules.lock

# Swith on the locker
touch $lock_file

# Adding content of .zman folder to .gitignore
if [ -d $ZMAN_PROJECT_PATH/.git ]; then
    ignore_string=.zman/*
    git_ignore=$ZMAN_PROJECT_PATH/.gitignore
    if [ ! -f $ZMAN_PROJECT_PATH/.gitignore ]; then
        # If .gitignore isn't present
        echo "Case 1"
        echo $ignore_string >> $git_ignore
    else
        # If .gitignore already exists,
        # check if this string is not present in file.
        echo "Case 2"
        grep -qxF $ignore_string $git_ignore || echo $ignore_string >> $git_ignore
    fi
fi

# Iterating over lines of .zman.modules
while read p; do
    # p is a line from the file
    if ! $ZMAN_DIR/zman_clone_module $p ; then
        exit 1
    fi
done <$ZMAN_MODULES_FILE

# Removing the lock file
rm $lock_file
