#!/bin/bash
path="$(pwd)"

while [[ $path != / ]];
do
    # Search files
    RESULT=$(find "$path" -maxdepth 1 -mindepth 1 "$@")
    if [ ! -z "$RESULT" ]; then
          echo "$RESULT"
          exit 0
    fi
    
    # One level up
    path="$(readlink -f "$path"/..)"
done 
